# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.1-stretch-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Install cmake, build-eseential since gem build with native extension needs it
      - run:
          name: Install cmake needed by rugged
          command: sudo apt-get install cmake

      - run:
          name: Install and start geckodriver
          command: |
            wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz &&
            tar -xvzf geckodriver* &&
            chmod +x geckodriver &&
            sudo mv geckodriver /usr/local/bin

      - run:
          name: Install the latest firefox
          command: |
            sudo sh -c "echo 'deb http://ftp.hr.debian.org/debian sid main' >> /etc/apt/sources.list" &&
            sudo apt-get update &&
            sudo apt-get install -t sid firefox &&
            firefox --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - v1-npm-install-{{ checksum "package-lock.json" }}
            - v1-npm-install

      - run: npm install

      # Store yarn / webpacker cache
      - save_cache:
          key: v1-npm-install-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec rake test

      - run:
          name: run react tests
          command: npm run test

      - run:
          name: run rubocop
          command: bundle exec rubocop

      - run:
          name: run eslint
          command: npm run lint

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
